# Generated by Django 2.2.7 on 2020-04-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_site', '0002_auto_20200413_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
        migrations.AddField(
            model_name='student',
            name='classes_taken',
            field=models.ManyToManyField(related_name='_student_classes_taken_+', to='dance_site.Student'),
        ),
    ]
