# Generated by Django 2.2.7 on 2020-04-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dance_site', '0003_auto_20200414_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes_taken',
        ),
        migrations.AddField(
            model_name='student',
            name='classes_taken',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dance_site.Class'),
        ),
    ]
