# Generated by Django 2.2.7 on 2020-04-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dance_site', '0004_auto_20200414_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes_taught',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dance_site.Class'),
        ),
    ]
