# Generated by Django 2.2.7 on 2020-04-14 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dance_site', '0007_auto_20200414_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='teaches_taught',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dance_site.Teacher'),
        ),
    ]
