# Generated by Django 2.2.7 on 2020-04-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dance_site', '0008_auto_20200414_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='teaches_taught',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teaches_taught',
        ),
    ]
