# Generated by Django 2.2.7 on 2020-04-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_site', '0009_auto_20200414_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes_taken',
        ),
        migrations.AddField(
            model_name='student',
            name='classes_taken',
            field=models.ManyToManyField(null=True, to='dance_site.Class'),
        ),
    ]
