# Generated by Django 2.2.7 on 2020-04-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance_site', '0010_auto_20200416_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classes_taken',
            field=models.ManyToManyField(to='dance_site.Class'),
        ),
    ]
