# Generated by Django 2.2.7 on 2020-04-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmessage',
            name='status_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
